name: 'Close inactive issues'
on:
  #workflow_dispatch:
  schedule:
   - cron: '0 1 * * *'


jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This application has not seen any responses in the last 10 days. This issue will be marked with Stale label and will be closed in 4 days. Comment if you want to keep this application open.'
          stale-pr-message: 'This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to contact the Fil+ Gov team to re-open the application if it is still being processed. Thank you!'
          close-issue-message: 'This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to contact the Fil+ Gov team to re-open the application if it is still being processed. Thank you!'
          days-before-stale: 14 # We will mark as stale at 14 days of inactivity
          days-before-close: 0  # We will close immediately after marking as stale
          days-before-pr-close: -1
          operations-per-run: 1000
          ascending: true
  
  notify_stale_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github
          
      - name: Install dependencies
        run: |
          npm install @octokit/rest node-fetch
          
      - name: Notify on stale issues
        run: node .github/scripts/notify_stale_issues.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
